Added kotlin gradle sample
trello/victor pull request #77
Opened 2020-12-02 11:42 UTC by arberg

2020-12-08 20:14 UTC, dlew requested changes

2020-12-08 20:14 UTC, dlew commented on README.md
> +```
I like providing these docs, but could we split them out into its own `# Usage (Kotlin Gradle)` section? I worry that interleaving these examples between two different types of Gradle files will be confusing.

2020-12-08 20:52 UTC, arberg commented
Yeah, that sounds like a good idea. I'll do that

2020-12-14 14:20 UTC, dlew approved these changes

2020-12-14 14:20 UTC, merged

2020-12-14 14:20 UTC, dlew commented
Thanks!